django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from survey.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('survey/',include('survey.urls')),
    path('tester/',include('tester.urls')),
    path('',IndexView.as_view(), name='home')
]

django_project/survey/urls.py
from django.urls import path
from . import views
app_name='aplication'
urlpatterns = [
    #ex : /survey/ =home
    path('', views.IndexView.as_view(), name='index'),
    #ex : /survey/5/ = access to object 5 of survey
    path('detail/<int:pk>/',views.DetailView.as_view(),name='detail'),
    #ex : /survey/5/ = access to object 5 of survey
    path('<int:pk>/resolves/',views.Resolves.as_view(),name='resolves'),
    #ex : /survey/5/ = access to object 5 of survey
    path('vote/<int:question_id>/',views.vote,name='vote'),
    path('questions/',views.AuthorCreateView.as_view(),name='questions'),
    path('answers/',views.ChoiceAnswer.as_view(),name='answers')
    
]

django_project/tester/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index')
    
]

django_project/crud/models.py
from django.db import models

# Create your models here.

django_project/survey/models.py
from django.db import models
from django.utils import timezone
import datetime
# models
class Question(models.Model):
    question_text= models.CharField(max_length=2000)
    pub_date=models.DateField("date publish")
    def __str__(self):
        return self.question_text+' at '+str(self.pub_date)
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
class Choice(models.Model):
    #on delete models cascade = delete all thins releted to Question so important
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choise_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    def __str__(self):
        return self.choise_text

django_project/tester/models.py
from django.db import models

# Create your models here.

django_project/crud/views.py
from django.shortcuts import render

# Create your views here.

django_project/survey/views.py
import imp
from secrets import choice
from django.shortcuts import render ,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from survey.models import Question,Choice
from django.urls import reverse
from django.views.generic import CreateView
from django.views import generic
#home

class AuthorCreateView(CreateView):
    model = Question
    fields = ['pub_date','question_text']
class ChoiceAnswer(CreateView):
    model= Choice
    fields=['question','choise_text']
    

class IndexView(generic.ListView):
    template_name='survey/index.html'
    context_object_name='latest_question_list'
    def get_queryset(self):

        #the parameter - means return things in reverse way
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):


    model=Question
    template_name='survey/detail.html'
    
class Resolves(generic.DeleteView):
    
    model=Question
    template_name='survey/vote.html'
# def index(request):
#     latest_question_list=Question.objects.all()
#     return render(request,'survey/index.html',{'latest_question_list':latest_question_list})

# def detail(request,question_id):
#     question=get_object_or_404(Question,pk=question_id)      
#     return render(request,'survey/detail.html',{'question':question})

# def resolves(request,question_id):
#     question=get_object_or_404(Question,pk=question_id)
#     return render(request,'survey/vote.html',{'question':question})

def vote(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    try:
        select_choice=question.choice_set.get(pk=request.POST["choice"])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'survey/detail.html',{
            'question':question,
            'error_message':"no elegiste una respuesta"
        })
    else:
        select_choice.votes +=1
        select_choice.save()
        return HttpResponseRedirect(reverse('aplication:resolves',args=(question.id,)))

    

django_project/tester/views.py
from django.shortcuts import render
from django.http import HttpResponse
def index(request):
    return HttpResponse("what's app new world, bitches"*2)
# Create your views here.

# Create your views here.

django_project/survey/templates/survey/choice_form.html
<form action="{% url 'survey/index.html' %}"  method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

django_project/survey/templates/survey/detail.html
<form action="{% url 'aplication:vote' question.id %}"method ='post'>
    {% comment %} be careful the line below is important to security propouse {% endcomment %}
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{question.question_text}}</h1></legend>
        {% if error_message %}
            <p><strong>{{error_message}}</strong></p>        
        {% endif %}
        {% for choice in question.choice_set.all %}
     
        <input 
        type="radio"
        name="choice"
        {% comment %} important this will not work properly
         in the future due to choice for loop is diferent
         than choice.id {% endcomment %}
        id="choice{{forloop.counter}}"
        value="{{choice.id}}"
        
        >
        <label for="choice{{choice.id}}">
            {{choice.choise_text}}
        </label>
        <br>


    
        {% endfor %}
    </fieldset>
    <input type="submit" value='Votar'>

</form>




{% comment %} 


{% if question %}
    <h1>{{question.question_text}}</h1>
    
    <ul>
    {% for unit in question.choice_set.all %}
     
        <li>{{unit.choise_text}}</li>
    
    {% endfor %}
</ul>
{% else %}
    <p>No surveys are avalilable</p>

{% endif %}  {% endcomment %}

django_project/survey/templates/survey/index.html
{% if latest_question_list %}
    <ul>
        {% for  question in latest_question_list%}
            <li><a href="{% url 'aplication:detail' question.id %}">{{question.question_text}}</a></li>
            {% endfor %}
        
    </ul>
{% else %}
    <p>No surveys are avalilable</p>

{% endif %}

django_project/survey/templates/survey/question_form.html
<form action= "{% url 'aplication:index'%}" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

django_project/survey/templates/survey/vote.html
{% if question %}
<H1>{{question.question_text}}</H1>
<h2>Total de votos</h2>
    <ul>
      {% for choice in question.choice_set.all %}
      {% comment %} use the scrip below to pluralize  {% endcomment %}
      {% comment %} You have {{ num_cherries }} cherr{{ num_cherries|pluralize:"y,ies" }}. {% endcomment %}
      <li>{{choice.choise_text}} tiene {{choice.votes}}</li>
      {% endfor %}
        
        
    </ul>
    <a href="{% url 'aplication:index' %}">Volver al inicio</a>
{% else %}
    <p>No surveys are avalilable</p>

{% endif %}